version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - API_TOKEN=1a5b1c0362c90fb6eec9c783fb472205be7ef3a73e5384587e097919083252ea
      - GOOGLE_API_KEY=AIzaSyBUu4gMtW-IIqTDEcmnQGBCCXyWQ5W4BaI
      - DATABASE_URL=postgresql://hackrx_user:hackrx_password@db:5432/hackrx_db
      - FAISS_INDEX_PATH=./data/faiss_index
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - DEBUG=True
      - LOG_LEVEL=INFO
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./fe
    ports:
      - "3000:3000"
    volumes:
      - ./fe:/app:cached
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development  # IMPORTANT: Keep this as development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEXT_TELEMETRY_DISABLED=1
    # IMPORTANT: Only run dev command, never build or start
    command: sh -c "rm -rf .next && npm install && npm run dev -- -H 0.0.0.0"
    stdin_open: true
    tty: true
    depends_on:
      - api
    networks:
      - app-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=hackrx_db
      - POSTGRES_USER=hackrx_user
      - POSTGRES_PASSWORD=hackrx_password
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  node_modules: